using System.Web.Script.Serialization;
using AlohaOrderOnLine.Infrastructure;
using AlohaOrderOnLine.Model;

namespace AlohaOrderOnLine.Service
{
    public class Orders
    {
        public string PutCreateOrder(string uri, string siteId)
        {
            var userJsonData = CreateJson();
            //var json = new JavaScriptSerializer().Serialize(userJsonData);
            // ejemplo1  string json = " {\"SiteId\":2,\"OrderId\":0,\"DesignId\":0,\"MenuId\":1000,\"PromiseDateTime\":\"2015-12-30T16:14:50.00\",\"LineItems\":[{\"$id\":\"380\",\"ItemLineNumber\":1,\"MenuItemId\":1077,\"SalesItemId\":2077,\"POSItemId\":14028,\"SpecialInstructions\":\"SpecialInstructions\",\"RecipientName\":\"RecipientName\",\"Quantity\":2,\"NextModifierSequenceNumber\":0,\"ItemOrderingMode\":\"02\",\"UnitPriceOverride\":0,\"EnablePriceOverride\":false}],\"OrderMode\":\"Delivery\",\"UpdateTimeDisabled\":false,\"PaymentMode\":\"PaidOnline\",\"OrderSource\":\"Web\",\"Destination\":\"\",\"ShouldManualRelease\":false,\"TaxJurisdictionId\":0,\"Customer\":{\"Email\":\"rolando.gomez@gmail.com\",\"FirstName\":\"Rolando\",\"LastName\":\"Gomez\",\"BusinessName\":\"SHS-123\",\"VoicePhone\":\"19286285\",\"VoicePhoneExtension\":\"123\",\"DepartmentName\":\"Desarrollo\",\"AltPhone\":\"29286285\",\"AltPhoneExtension\":\"123\",\"FavoriteSiteId\":2,\"LoyaltyCardNumber\":\"sample\",\"SecondaryEmailAddress\":\"rolando.starpms@hotmail.com\",\"Addresses\":[{\"AddressId\":0,\"AddressType\":\"\",\"IsDefault\":false,\"Description\":\"\",\"DepartmentName\":\"\",\"AddressLine1\":\"\",\"AddressLine2\":\"\",\"City\":\"Madrid\",\"State\":\"MA\",\"Postal\":\"28016\"}],\"FacebookId\":0},\"CustomerAddressForOrder\":{\"AddressId\":0,\"AddressType\":\"\",\"IsDefault\":false,\"Description\":\"\",\"DepartmentName\":\"\",\"AddressLine1\":\"\",\"AddressLine2\":\"\",\"City\":\"Madrid\",\"State\":\"MA\",\"Postal\":\"28016\"},\"SpecialInstructions\":\"\",\"LoyaltyNumber\":\"\",\"CompId\":0,\"ReferenceNumber\":0} ";
            // ejemplo 1 con dos items string json = "{\"SiteId\":2,\"OrderId\":0,\"DesignId\":0,\"MenuId\":1000,\"PromiseDateTime\":\"2015-12-30T16:14:50.00\",\"LineItems\":[{\"$id\":\"380\",\"ItemLineNumber\":1,\"MenuItemId\":1077,\"SalesItemId\":2077,\"POSItemId\":14028,\"SpecialInstructions\":\"SpecialInstructions\",\"RecipientName\":\"RecipientName\",\"Quantity\":1,\"NextModifierSequenceNumber\":0,\"ItemOrderingMode\":\"02\",\"UnitPriceOverride\":0,\"EnablePriceOverride\":false},{\"$id\":\"381\",\"ItemLineNumber\":2,\"MenuItemId\":1077,\"SalesItemId\":2077,\"POSItemId\":14028,\"SpecialInstructions\":\"SpecialInstructions\",\"RecipientName\":\"RecipientName\",\"Quantity\":1,\"NextModifierSequenceNumber\":0,\"ItemOrderingMode\":\"02\",\"UnitPriceOverride\":0,\"EnablePriceOverride\":false}],\"OrderMode\":\"Delivery\",\"UpdateTimeDisabled\":false,\"PaymentMode\":\"PaidOnline\",\"OrderSource\":\"Web\",\"Destination\":\"\",\"ShouldManualRelease\":false,\"TaxJurisdictionId\":0,\"Customer\":{\"Email\":\"rolando.gomez@gmail.com\",\"FirstName\":\"Rolando\",\"LastName\":\"Gomez\",\"BusinessName\":\"SHS-123\",\"VoicePhone\":\"19286285\",\"VoicePhoneExtension\":\"123\",\"DepartmentName\":\"Desarrollo\",\"AltPhone\":\"29286285\",\"AltPhoneExtension\":\"123\",\"FavoriteSiteId\":2,\"LoyaltyCardNumber\":\"sample\",\"SecondaryEmailAddress\":\"rolando.starpms@hotmail.com\",\"Addresses\":[{\"AddressId\":0,\"AddressType\":\"\",\"IsDefault\":false,\"Description\":\"\",\"DepartmentName\":\"\",\"AddressLine1\":\"\",\"AddressLine2\":\"\",\"City\":\"Madrid\",\"State\":\"MA\",\"Postal\":\"28016\"}],\"FacebookId\":0},\"CustomerAddressForOrder\":{\"AddressId\":0,\"AddressType\":\"\",\"IsDefault\":false,\"Description\":\"\",\"DepartmentName\":\"\",\"AddressLine1\":\"\",\"AddressLine2\":\"\",\"City\":\"Madrid\",\"State\":\"MA\",\"Postal\":\"28016\"},\"SpecialInstructions\":\"\",\"LoyaltyNumber\":\"\",\"CompId\":0,\"ReferenceNumber\":0}";
            // ejemplo con modificador string json = "{\"SiteId\":2,\"OrderId\":0,\"DesignId\":0,\"MenuId\":1000,\"PromiseDateTime\":\"2015-12-30T16:14:50.00\",\"LineItems\":[{\"$id\":\"374\",\"ItemLineNumber\":1,\"SalesItemId\":2071,\"MenuItemId\":1071,\"SpecialInstructions\":\"sample string 4\",\"RecipientName\":\"sample string 5\",\"Quantity\":1,\"ItemOrderingMode\":0,\"UnitPriceOverride\":1,\"EnablePriceOverride\":false,\"Modifiers\":[{\"SequenceNumber\":1,\"ItemOptionGroupId\":8002,\"SalesItemOptionId\":2320,\"Action\":0,\"DefaultAction\":0,\"ItemLineNumber\":1,\"Quantity\":1}]}],\"OrderMode\":\"Delivery\",\"UpdateTimeDisabled\":false,\"PaymentMode\":0,\"Customer\":{\"Email\":\"rolando.gomez@gmail.com\",\"FirstName\":\"Rolando\",\"LastName\":\"Gomez\",\"BusinessName\":\"SHS-123\",\"VoicePhone\":\"19286285\",\"VoicePhoneExtension\":\"123\",\"DepartmentName\":\"Desarrollo\",\"AltPhone\":\"29286285\",\"AltPhoneExtension\":\"123\",\"FavoriteSiteId\":2,\"LoyaltyCardNumber\":\"sample\",\"SecondaryEmailAddress\":\"rolando.starpms@hotmail.com\",\"Addresses\":[{\"AddressId\":0,\"AddressType\":\"\",\"IsDefault\":false,\"Description\":\"\",\"DepartmentName\":\"\",\"AddressLine1\":\"\",\"AddressLine2\":\"\",\"City\":\"Madrid\",\"State\":\"MA\",\"Postal\":\"28016\"}],\"FacebookId\":0}}";
            // ejemplo con el mismo modificador 2 veces string json = "{\"SiteId\":2,\"OrderId\":0,\"DesignId\":0,\"MenuId\":1000,\"PromiseDateTime\":\"2015-12-30T16:14:50.00\",\"LineItems\":[{\"$id\":\"374\",\"ItemLineNumber\":1,\"SalesItemId\":2071,\"MenuItemId\":1071,\"SpecialInstructions\":\"sample string 4\",\"RecipientName\":\"sample string 5\",\"Quantity\":1,\"ItemOrderingMode\":0,\"UnitPriceOverride\":1,\"EnablePriceOverride\":false,\"Modifiers\":[{\"SequenceNumber\":1,\"ItemOptionGroupId\":8002,\"SalesItemOptionId\":2320,\"Action\":0,\"DefaultAction\":0,\"ItemLineNumber\":1,\"Quantity\":1},{\"SequenceNumber\":2,\"ItemOptionGroupId\":8002,\"SalesItemOptionId\":2320,\"Action\":0,\"DefaultAction\":0,\"ItemLineNumber\":1,\"Quantity\":1}]}],\"OrderMode\":\"Delivery\",\"UpdateTimeDisabled\":false,\"PaymentMode\":0,\"Customer\":{\"Email\":\"rolando.gomez@gmail.com\",\"FirstName\":\"Rolando\",\"LastName\":\"Gomez\",\"BusinessName\":\"SHS-123\",\"VoicePhone\":\"19286285\",\"VoicePhoneExtension\":\"123\",\"DepartmentName\":\"Desarrollo\",\"AltPhone\":\"29286285\",\"AltPhoneExtension\":\"123\",\"FavoriteSiteId\":2,\"LoyaltyCardNumber\":\"sample\",\"SecondaryEmailAddress\":\"rolando.starpms@hotmail.com\",\"Addresses\":[{\"AddressId\":0,\"AddressType\":\"\",\"IsDefault\":false,\"Description\":\"\",\"DepartmentName\":\"\",\"AddressLine1\":\"\",\"AddressLine2\":\"\",\"City\":\"Madrid\",\"State\":\"MA\",\"Postal\":\"28016\"}],\"FacebookId\":0}}";
            // ejemplo dos modificadores distintos string json = "{\"SiteId\":2,\"OrderId\":0,\"DesignId\":0,\"MenuId\":1000,\"PromiseDateTime\":\"2015-12-30T16:14:50.00\",\"LineItems\":[{\"$id\":\"374\",\"ItemLineNumber\":1,\"SalesItemId\":2071,\"MenuItemId\":1071,\"SpecialInstructions\":\"sample string 4\",\"RecipientName\":\"sample string 5\",\"Quantity\":1,\"ItemOrderingMode\":0,\"UnitPriceOverride\":1,\"EnablePriceOverride\":false,\"Modifiers\":[{\"SequenceNumber\":1,\"ItemOptionGroupId\":8002,\"SalesItemOptionId\":2320,\"Action\":0,\"DefaultAction\":0,\"ItemLineNumber\":1,\"Quantity\":1},{\"SequenceNumber\":2,\"ItemOptionGroupId\":8002,\"SalesItemOptionId\":2315,\"Action\":0,\"DefaultAction\":0,\"ItemLineNumber\":1,\"Quantity\":1}]}],\"OrderMode\":\"Delivery\",\"UpdateTimeDisabled\":false,\"PaymentMode\":0,\"Customer\":{\"Email\":\"rolando.gomez@gmail.com\",\"FirstName\":\"Rolando\",\"LastName\":\"Gomez\",\"BusinessName\":\"SHS-123\",\"VoicePhone\":\"19286285\",\"VoicePhoneExtension\":\"123\",\"DepartmentName\":\"Desarrollo\",\"AltPhone\":\"29286285\",\"AltPhoneExtension\":\"123\",\"FavoriteSiteId\":2,\"LoyaltyCardNumber\":\"sample\",\"SecondaryEmailAddress\":\"rolando.starpms@hotmail.com\",\"Addresses\":[{\"AddressId\":0,\"AddressType\":\"\",\"IsDefault\":false,\"Description\":\"\",\"DepartmentName\":\"\",\"AddressLine1\":\"\",\"AddressLine2\":\"\",\"City\":\"Madrid\",\"State\":\"MA\",\"Postal\":\"28016\"}],\"FacebookId\":0}}";
            string json = "{\"SiteId\":2,\"OrderId\":0,\"DesignId\":0,\"MenuId\":1000,\"PromiseDateTime\":\"2015-12-30T16:14:50.00\",\"LineItems\":[{\"$id\":\"374\",\"ItemLineNumber\":1,\"SalesItemId\":2071,\"MenuItemId\":1071,\"SpecialInstructions\":\"sample string 4\",\"RecipientName\":\"sample string 5\",\"Quantity\":1,\"ItemOrderingMode\":0,\"UnitPriceOverride\":1,\"EnablePriceOverride\":false,\"Modifiers\":[{\"SequenceNumber\":1,\"ItemOptionGroupId\":8002,\"SalesItemOptionId\":2320,\"Action\":0,\"DefaultAction\":0,\"ItemLineNumber\":1,\"Quantity\":1},{\"SequenceNumber\":2,\"ItemOptionGroupId\":8002,\"SalesItemOptionId\":2315,\"Action\":0,\"DefaultAction\":0,\"ItemLineNumber\":1,\"Quantity\":1}]},{\"$id\":\"375\",\"ItemLineNumber\":2,\"SalesItemId\":2071,\"MenuItemId\":1071,\"SpecialInstructions\":\"sample string 4\",\"RecipientName\":\"sample string 5\",\"Quantity\":1,\"ItemOrderingMode\":0,\"UnitPriceOverride\":1,\"EnablePriceOverride\":false,\"Modifiers\":[{\"SequenceNumber\":1,\"ItemOptionGroupId\":8002,\"SalesItemOptionId\":2320,\"Action\":0,\"DefaultAction\":0,\"ItemLineNumber\":2,\"Quantity\":1},{\"SequenceNumber\":2,\"ItemOptionGroupId\":8002,\"SalesItemOptionId\":2315,\"Action\":0,\"DefaultAction\":0,\"ItemLineNumber\":2,\"Quantity\":1}]}],\"OrderMode\":\"Delivery\",\"UpdateTimeDisabled\":false,\"PaymentMode\":0,\"Customer\":{\"Email\":\"rolando.gomez@gmail.com\",\"FirstName\":\"Rolando\",\"LastName\":\"Gomez\",\"BusinessName\":\"SHS-123\",\"VoicePhone\":\"19286285\",\"VoicePhoneExtension\":\"123\",\"DepartmentName\":\"Desarrollo\",\"AltPhone\":\"29286285\",\"AltPhoneExtension\":\"123\",\"FavoriteSiteId\":2,\"LoyaltyCardNumber\":\"sample\",\"SecondaryEmailAddress\":\"rolando.starpms@hotmail.com\",\"Addresses\":[{\"AddressId\":0,\"AddressType\":\"\",\"IsDefault\":false,\"Description\":\"\",\"DepartmentName\":\"\",\"AddressLine1\":\"\",\"AddressLine2\":\"\",\"City\":\"Madrid\",\"State\":\"MA\",\"Postal\":\"28016\"}],\"FacebookId\":0}}";
            
            
            
            
            //string json = "{\"SiteId\":2,\"OrderId\":1,\"DesignId\":2,\"MenuId\":1000,\"PromiseDateTime\":\"2016-01-04T12:02:47.4762238-05:00\",\"LineItems\":[{\"$id\":\"2\",\"ItemLineNumber\":1,\"SalesItemId\":2,\"MenuItemId\":3,\"SpecialInstructions\":\"sample string 4\",\"RecipientName\":\"sample string 5\",\"Quantity\":6,\"NextModifierSequenceNumber\":7,\"ItemOrderingMode\":0,\"UnitPriceOverride\":1,\"EnablePriceOverride\":true,\"Section1Type\":0,\"Section2Type\":0,\"Section3Type\":0,\"Section4Type\":0,\"Modifiers\":[{\"$id\":\"3\",\"SequenceNumber\":1,\"ItemOptionGroupId\":2,\"SalesItemOptionId\":3,\"Action\":0,\"DefaultAction\":0,\"ItemLineNumber\":4,\"ParentSequenceNumber\":5,\"Quantity\":6,\"IsOnEntireItem\":true,\"IsOnSection1\":true,\"IsOnSection2\":true,\"IsOnSection3\":true,\"IsOnSection4\":true,\"FreeQuantity\":1,\"Modifiers\":[{\"$ref\":\"3\"},{\"$ref\":\"3\"}]},{\"$ref\":\"3\"}]},{\"$ref\":\"2\"}],\"ComboItems\":[{\"$id\":\"4\",\"PromoId\":1,\"PromoType\":0,\"Price\":2,\"WebSalesGroupLineItems\":[{\"$id\":\"5\",\"WebSalesGroupId\":1,\"LineItemNumber\":2,\"GroupLineId\":3,\"MenuItemName\":\"sample string 4\",\"SalesItemId\":5},{\"$ref\":\"5\"}]},{\"$ref\":\"4\"}],\"OrderMode\":1,\"UpdateTimeDisabled\":true,\"PaymentMode\":0,\"OrderSource\":0,\"Destination\":0,\"ShouldManualRelease\":true,\"TaxJurisdictionId\":1,\"Customer\":{\"$id\":\"6\",\"CustomerId\":\"2e8a068c-0d71-4e99-bdef-0a6ddf91cfcd\",\"EMail\":\"rolando.gomez@gmail.com\",\"FirstName\":\"Rolando\",\"LastName\":\"Gomez\",\"BusinessName\":\"shs 4\",\"VoicePhone\":\"19286285\",\"VoicePhoneExtension\":\"123\",\"DepartmentName\":\"sample\",\"AltPhone\":\"21286285\",\"AltPhoneExtension\":\"123\",\"FavoriteSiteId\":2,\"LoyaltyCardNumber\":\"sample\",\"SecondaryEmailAddress\":\"sample.algo@algo.com\",\"Addresses\":[{\"$id\":\"7\",\"AddressId\":0,\"AddressType\":\"\",\"IsDefault\":false,\"Description\":\"\",\"DepartmentName\":\"\",\"AddressLine1\":\"\",\"AddressLine2\":\"\",\"City\":\"Madrid\",\"State\":\"MA\",\"Postal\":\"28016\"},{\"$ref\":\"7\"}],\"Birthday\":\"2016-01-04T12:02:47.4918238-05:00\",\"LoyaltyZipCode\":\"sample\"},\"CustomerAddressForOrder\":{\"$ref\":\"7\"},\"SpecialInstructions\":\"sample\",\"LoyaltyNumber\":\"sample6\",\"CompId\":1,\"ReferenceNumber\":1,\"BypassLoyalty\":true}";
            //string json = "{\"SiteId\":2,\"OrderId\":0,\"DesignId\":0,\"MenuId\":1000,\"PromiseDateTime\":\"2015-12-30T16:14:50.00\",\"LineItems\":[{\"$id\":\"374\",\"ItemLineNumber\":1,\"SalesItemId\":2071,\"MenuItemId\":1071,\"SpecialInstructions\":\"sample string 4\",\"RecipientName\":\"sample string 5\",\"Quantity\":1,\"NextModifierSequenceNumber\":1,\"ItemOrderingMode\":0,\"UnitPriceOverride\":1,\"EnablePriceOverride\":false,\"Modifiers\":[{\"$id\":\"678\",\"SequenceNumber\":1,\"ItemOptionGroupId\":2320,\"SalesItemOptionId\":1,\"Action\":0,\"DefaultAction\":0,\"ItemLineNumber\":4,\"ParentSequenceNumber\":5,\"Quantity\":2}]}],\"OrderMode\":\"Delivery\",\"UpdateTimeDisabled\":false,\"PaymentMode\":0,\"Customer\":{\"Email\":\"rolando.gomez@gmail.com\",\"FirstName\":\"Rolando\",\"LastName\":\"Gomez\",\"BusinessName\":\"SHS-123\",\"VoicePhone\":\"19286285\",\"VoicePhoneExtension\":\"123\",\"DepartmentName\":\"Desarrollo\",\"AltPhone\":\"29286285\",\"AltPhoneExtension\":\"123\",\"FavoriteSiteId\":2,\"LoyaltyCardNumber\":\"sample\",\"SecondaryEmailAddress\":\"rolando.starpms@hotmail.com\",\"Addresses\":[{\"AddressId\":0,\"AddressType\":\"\",\"IsDefault\":false,\"Description\":\"\",\"DepartmentName\":\"\",\"AddressLine1\":\"\",\"AddressLine2\":\"\",\"City\":\"Madrid\",\"State\":\"MA\",\"Postal\":\"28016\"}],\"FacebookId\":0}}";
            //string json = "{\"SiteId\":2,\"OrderId\":0,\"DesignId\":0,\"MenuId\":1000,\"PromiseDateTime\":\"2015-12-30T16:14:50.00\",\"LineItems\":[{\"$id\":\"374\",\"ItemLineNumber\":1,\"SalesItemId\":2071,\"MenuItemId\":1071,\"SpecialInstructions\":\"sample string 4\",\"RecipientName\":\"sample string 5\",\"Quantity\":2,\"NextModifierSequenceNumber\":1,\"ItemOrderingMode\":0,\"UnitPriceOverride\":1,\"EnablePriceOverride\":false,\"Modifiers\":[{\"SequenceNumber\":1,\"ItemOptionGroupId\":2320,\"SalesItemOptionId\":20526,\"Action\":0,\"DefaultAction\":0,\"ItemLineNumber\":1,\"ParentSequenceNumber\":5,\"Quantity\":1}]}],\"OrderMode\":\"Delivery\",\"UpdateTimeDisabled\":false,\"PaymentMode\":0,\"Customer\":{\"Email\":\"rolando.gomez@gmail.com\",\"FirstName\":\"Rolando\",\"LastName\":\"Gomez\",\"BusinessName\":\"SHS-123\",\"VoicePhone\":\"19286285\",\"VoicePhoneExtension\":\"123\",\"DepartmentName\":\"Desarrollo\",\"AltPhone\":\"29286285\",\"AltPhoneExtension\":\"123\",\"FavoriteSiteId\":2,\"LoyaltyCardNumber\":\"sample\",\"SecondaryEmailAddress\":\"rolando.starpms@hotmail.com\",\"Addresses\":[{\"AddressId\":0,\"AddressType\":\"\",\"IsDefault\":false,\"Description\":\"\",\"DepartmentName\":\"\",\"AddressLine1\":\"\",\"AddressLine2\":\"\",\"City\":\"Madrid\",\"State\":\"MA\",\"Postal\":\"28016\"}],\"FacebookId\":0}}";
            //string json = "{\"SiteId\":2,\"OrderId\":0,\"DesignId\":0,\"MenuId\":1000,\"PromiseDateTime\":\"2015-12-30T16:14:50.00\",\"LineItems\":[{\"$id\":\"374\",\"ItemLineNumber\":1,\"SalesItemId\":2071,\"MenuItemId\":1071,\"SpecialInstructions\":\"sample string 4\",\"RecipientName\":\"sample string 5\",\"Quantity\":1,\"NextModifierSequenceNumber\":1,\"ItemOrderingMode\":0,\"UnitPriceOverride\":1,\"EnablePriceOverride\":false,\"Modifiers\":[{\"SequenceNumber\":1,\"ItemOptionGroupId\":2320,\"SalesItemOptionId\":20526,\"Action\":0,\"DefaultAction\":0,\"ItemLineNumber\":1,\"ParentSequenceNumber\":5,\"Quantity\":1}]},{\"$id\":\"384\",\"ItemLineNumber\":1,\"SalesItemId\":2081,\"MenuItemId\":1081,\"SpecialInstructions\":\"sample string 4\",\"RecipientName\":\"sample string 5\",\"Quantity\":2,\"NextModifierSequenceNumber\":1,\"ItemOrderingMode\":0,\"UnitPriceOverride\":1,\"EnablePriceOverride\":false,\"Modifiers\":[{\"SequenceNumber\":1,\"ItemOptionGroupId\":2320,\"SalesItemOptionId\":20526,\"Action\":0,\"DefaultAction\":0,\"ItemLineNumber\":1,\"ParentSequenceNumber\":5,\"Quantity\":1}]}],\"OrderMode\":\"Delivery\",\"UpdateTimeDisabled\":false,\"PaymentMode\":0,\"Customer\":{\"Email\":\"rolando.gomez@gmail.com\",\"FirstName\":\"Rolando\",\"LastName\":\"Gomez\",\"BusinessName\":\"SHS-123\",\"VoicePhone\":\"19286285\",\"VoicePhoneExtension\":\"123\",\"DepartmentName\":\"Desarrollo\",\"AltPhone\":\"29286285\",\"AltPhoneExtension\":\"123\",\"FavoriteSiteId\":2,\"LoyaltyCardNumber\":\"sample\",\"SecondaryEmailAddress\":\"rolando.starpms@hotmail.com\",\"Addresses\":[{\"AddressId\":0,\"AddressType\":\"\",\"IsDefault\":false,\"Description\":\"\",\"DepartmentName\":\"\",\"AddressLine1\":\"\",\"AddressLine2\":\"\",\"City\":\"Madrid\",\"State\":\"MA\",\"Postal\":\"28016\"}],\"FacebookId\":0}}";
            //json = "{\"Customer\":{\"CustomerId\":{},\"Email\":\"rolando.starpms@hotmail.com\",\"FirstName\":\"Emiliano\",\"LastName\":\"Gomez\",\"BusinessName\":\"SHS-\",\"VoicePhone\":\"19286285\",\"VoicePhoneExtension\":\"123\",\"DepartmentName\":\"Desarrollo\",\"AltPhone\":\"29286285\",\"AltPhoneExtension\":\"123\",\"FavoriteSiteId\":2,\"LoyaltyCardNumber\":\"sample\",\"SecondaryEmailAddress\":\"sample\",\"Addresses\":[]},\"Password\":\"1234567890\",\"SecurityQuestion\":\"23456789\",\"SecurityAnswer\":\"asdfasdf\"}";
            return PutMethod.PutRequest(uri + "Orders/" + siteId + "?verbose=True", json);
        }


         private object CreateJson()
        {
            var obj = new InOrderModel
            {
                SiteId = 0,
                OrderId = 0,
                DesignId = 0,
                MenuId = 0,



            };
            return obj;
        }
    }
}
